name: CHANGELOG Misspell
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    paths:
      - .changelog/*
      - go.sum
      - CHANGELOG.md

jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version-file: go.mod
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/client9/misspell/cmd/misspell
      - run: misspell -error -source text CHANGELOG.md .changelog
